#!/bin/bash

# DEEZER QUERY
clear
printf "\rProgress: [%-50s] %d%%" "$(printf '#%.0s' $(seq 1 $((0 * 50 / 6))))" "$((0 * 100 / 6))"
playlist_data_raw=$(curl -sL $1 | grep -oP '<script>(.*?)<\/script>')

playlist_data="${playlist_data_raw//<script>/}"
playlist_data="${playlist_data//<\/script>/}"
playlist_json=$(echo "$playlist_data" | grep -oP '{.*}')

playlist_title=$(echo "$playlist_json" | jq -r '.DATA.TITLE')
mapfile -t songs < <(echo "$playlist_json" | jq '.SONGS.data[] | "\(.SNG_TITLE) by \(.ART_NAME)"')
printf "\rProgress: [%-50s] %d%%" "$(printf '#%.0s' $(seq 1 $((1 * 50 / 5))))" "$((1 * 100 / 5))"

# SPOTIFY
if [ -e "token.json" ]; then
    # Calculate the current time and the time one hour ago
    current_time=$(date +%s)
    one_hour_ago=$((current_time - 3600))

    # Get the file's last modification time
    file_mtime=$(stat -c %Y "token.json")

    # Check if the file is older than one hour
    if [ "$file_mtime" -lt "$one_hour_ago" ]; then
        rm "token.json"
    fi
fi

if [ ! -e "token.json" ]; then
  client_id=$(jq -r '.client_id' secret.json)

  python3 -m python_server > /dev/null 2>&1 &

  xdg-open "https://accounts.spotify.com/en/authorize?client_id=$client_id&response_type=token&scope=playlist-modify-public&show_dialog=false&redirect_uri=http://localhost:8000" > /dev/null 2>&1 &

  while [ ! -e "token.json" ]; do
      sleep 1
  done
fi

access_token=$(jq -r '.access_token' token.json)
printf "\rProgress: [%-50s] %d%%" "$(printf '#%.0s' $(seq 1 $((2 * 50 / 5))))" "$((2 * 100 / 5))"

user_infos=$(curl -s --request GET \
  --url https://api.spotify.com/v1/me \
  --header "Authorization: Bearer $access_token")

user_id=$(echo "$user_infos" | jq -r '.id')
printf "\rProgress: [%-50s] %d%%" "$(printf '#%.0s' $(seq 1 $((3 * 50 / 5))))" "$((3 * 100 / 5))"

playlist_data=$(curl -s --request POST \
  --url "https://api.spotify.com/v1/users/$user_id/playlists" \
  --header "Authorization: Bearer $access_token" \
  --header 'Content-Type: application/json' \
  --data "{
    \"name\": \"$playlist_title\",
    \"description\": \"A computer did that\",
    \"public\": true
  }")
playlist_id=$(echo "$playlist_data" | jq -r '.id')
printf "\rProgress: [%-50s] %d%%" "$(printf '#%.0s' $(seq 1 $((4 * 50 / 5))))" "$((4 * 100 / 5))"

for element in "${songs[@]}"; do
  song_url=$(echo "https://api.spotify.com/v1/search?q=$element&type=track&market=FR&limit=1" | sed 's/["]//g' | sed 's/ /%20/g')
  song_data=$(curl -s --request GET \
    --url "$song_url" \
    --header "Authorization: Bearer $access_token")
  song_id=$(echo "$song_data" | jq -r '.tracks.items[].id')
  
  curl -s --request POST \
    --url "https://api.spotify.com/v1/playlists/$playlist_id/tracks" \
    --header "Authorization: Bearer $access_token" \
    --header 'Content-Type: application/json' \
    --data "{
      \"uris\": [
          \"spotify:track:$song_id\"
      ],
      \"position\": 0
  }" > /dev/null 2>&1
done
printf "\rProgress: [%-50s] %d%%" "$(printf '#%.0s' $(seq 1 $((5 * 50 / 5))))" "$((5 * 100 / 5))"